[project]

name = "test-analysis-bot"
version = "0.1.2"
description = "Keep tabs on unreliable tests."
readme = "README.md"
license = "MIT"

requires-python = "^3.13"

[tool.poetry]

package-mode = false

[tool.poetry.dependencies]

# Web
django = "^5.2.9"
django-browser-reload = "^1.21"
django-cors-headers = "*"
django-crispy-forms = "^2.5"
crispy-bootstrap5 = "*" # styling for 'django-crispy-forms'
django-debug-toolbar = "^6.1"
django-tables2 = "^2.8.0"

# API
django-ninja = "^1.5.1"

# Storage
dj-database-url = "*"
psycopg2-binary = "^2.9.11"
redis = "^7.1.0"

# Integrations
pygithub = "^2.8.1"
slack-sdk = "^3.39.0"

# Utilities
django-extensions = "*"
django-user-agents = "^0.4.0"
markdown = "^3.10"
minilog = "*"
unidecode = "^1.4.0"

# Deployment
gunicorn = "^23.0.0"
whitenoise = "^6.11.0"

[tool.poetry.group.dev.dependencies]

# Formatting
black = "^25.12.0"
isort = "^7.0.0"
djlint = "^1.36.4"

# Linting
mypy = "^1.19.0"
django-stubs = { version = "^5.2.7", extras = ["compatible-mypy"] }
types-markdown = "*"
types-requests = "*"

# Testing
pytest = "^9.0.2"
pytest-django = "*"
pytest-describe = "*"
pytest-expecter = "*"
pytest-mock = "*"
pytest-randomly = "*"

# Coverage
pytest-cov = "*"
coveragespace = "^6.1"

# Utilities
watchdog = "^6.0"

[tool.poetry.group.docs.dependencies]

# UML
pylint = "*"
pygraphviz = "*"

[tool.black]

quiet = true

[tool.isort]

profile = "black"

known_django = "django"
sections = "FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"

[tool.djlint]

profile = "django"

blank_line_before_tag = "block"
blank_line_after_tag = "load,extends,endblock"

quiet = true

[tool.mypy]

ignore_missing_imports = true
no_implicit_optional = true
check_untyped_defs = true

exclude = ".+/migrations/.+"

cache_dir = ".cache/mypy/"

plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]

django_settings_module = "config.settings.local"

[tool.pytest.ini_options]

DJANGO_SETTINGS_MODULE = "config.settings.test"

log_level = "DEBUG"

cache_dir = ".cache/pytest/"

addopts = """
--strict-markers
--pdbcls=tests.debugger:Debugger

--quiet
-r sxX
--show-capture=log

--fail-on-template-vars

--junit-xml=test-results/junit.xml

--cov=tab
--cov-report=html
--cov-report=term-missing:skip-covered
--no-cov-on-fail
"""

markers = []

filterwarnings = [
    "ignore::pytest.PytestCollectionWarning",
    "ignore::django.utils.deprecation.RemovedInDjango60Warning",
    "ignore::DeprecationWarning:pydantic._internal._config:",
    "ignore::DeprecationWarning:ninja.orm.metaclass:"
]
