# Generated by Django 5.2 on 2025-07-26 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0048_more_help_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("failure_rate", models.FloatField()),
                ("block_rate", models.FloatField()),
                ("average_duration", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="projects.test",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Histories",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["test", "timestamp"],
                        name="metrics_his_test_id_5c29d7_idx",
                    )
                ],
            },
        ),
    ]
