# Generated by Django 5.2.5 on 2025-09-11 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0003_subscription"),
        ("projects", "0053_suite_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="history",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert",
                to="metrics.history",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="projects.project",
            ),
        ),
    ]
