# Generated by Django 5.2.5 on 2025-09-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_organization_slack_bot_token"),
        ("metrics", "0004_subscription_require_project"),
        ("projects", "0053_suite_parent"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("team", "project", "suite", "test")},
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("organization", "slack_channel_name")},
        ),
    ]
