# Generated by Django 5.2.6 on 2025-09-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0005_unique_teams_and_subscriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="alerted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
