# Generated by Django 5.2.6 on 2025-09-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0006_team_alerted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
