# Generated by Django 5.2.6 on 2025-09-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0008_history_result"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"ordering": ["team", "project"]},
        ),
    ]
