# Generated by Django 5.2.8 on 2025-11-06 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0009_alter_subscription_options"),
        ("projects", "0060_alter_test_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="test",
            field=models.ForeignKey(
                default=1,  # previous alerts need to be deleted first
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="projects.test",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="alert",
            name="history",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert",
                to="metrics.history",
            ),
        ),
    ]
