# Generated by Django 6.0.2 on 2026-02-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0010_alert_test_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="slack_channel_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
