# Generated by Django 6.0.5 on 2026-06-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0011_team_slack_channel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="slack_channel_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Slack Channel ID"
            ),
        ),
    ]
