# Generated by Django 6.0.6 on 2026-06-25 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0012_alter_team_slack_channel_id"),
        ("projects", "0066_suite_average_setup_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuiteHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("average_setup_duration", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history",
                        to="projects.run",
                    ),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="projects.suite",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Suite histories",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["suite", "timestamp"],
                        name="metrics_sui_suite_i_06890c_idx",
                    )
                ],
            },
        ),
    ]
