# Generated by Django 6.0.6 on 2026-07-17 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0014_rename_history_testhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testhistory",
            options={
                "ordering": ["-timestamp"],
                "verbose_name_plural": "Test histories",
            },
        ),
        migrations.RenameIndex(
            model_name="testhistory",
            new_name="metrics_tes_test_id_c13735_idx",
            old_name="metrics_his_test_id_5c29d7_idx",
        ),
    ]
