# Generated by Django 5.2 on 2025-04-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="branch",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="test",
            name="commit",
            field=models.CharField(default="", max_length=100),
        ),
    ]
