# Generated by Django 5.2 on 2025-04-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_test_branch_test_commit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="test",
            old_name="branch",
            new_name="original_branch",
        ),
        migrations.RenameField(
            model_name="test",
            old_name="commit",
            new_name="original_commit",
        ),
        migrations.AddField(
            model_name="project",
            name="default_branch",
            field=models.CharField(default="main", max_length=100),
        ),
    ]
