# Generated by Django 5.2 on 2025-04-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_result_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
    ]
