# Generated by Django 5.2 on 2025-04-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_test_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="average_duration",
            field=models.FloatField(default=-1),
        ),
    ]
