# Generated by Django 5.2 on 2025-04-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_test_average_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="default_branch",
        ),
        migrations.AddField(
            model_name="project",
            name="default_branches",
            field=models.JSONField(default=["main"]),
        ),
    ]
