# Generated by Django 5.2 on 2025-04-12 00:39

from django.db import migrations, models

import tab.projects.constants


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_project_default_branchs"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="failure_rate",
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name="project",
            name="default_branches",
            field=models.JSONField(default=tab.projects.constants.get_default_branches),
        ),
    ]
