# Generated by Django 5.2 on 2025-04-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_alter_result_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="enabled",
            field=models.BooleanField(default=False),
        ),
    ]
