# Generated by Django 5.2 on 2025-04-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_test_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="error_indicators",
            field=models.JSONField(default=list),
        ),
    ]
