# Generated by Django 5.2 on 2025-04-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_project_error_indicators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="result",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="test",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
