# Generated by Django 5.2 on 2025-04-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_result_final"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="block_rate",
            field=models.FloatField(
                default=-1, help_text="Effective failure rate with reruns excluded"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="failure_rate",
            field=models.FloatField(
                default=-1, help_text="Failure rate on original and default branches"
            ),
        ),
    ]
