# Generated by Django 5.2 on 2025-04-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_test_block_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="block_rate",
            field=models.FloatField(
                default=-1,
                help_text="Effective failure rate with reruns and disabled excluded",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="failure_rate",
            field=models.FloatField(
                default=-1,
                help_text="Total failure rate on significant branches including reruns",
            ),
        ),
    ]
