# Generated by Django 5.2 on 2025-04-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_alter_rate_help"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="enabled",
            field=models.BooleanField(
                default=False, help_text="Test is allowed to block merges and releases"
            ),
        ),
    ]
