# Generated by Django 5.2 on 2025-04-17 15:20

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_alter_enabled_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="test_inactive_threshold",
            field=models.DurationField(
                default=datetime.timedelta(days=7),
                help_text="Tests older than this will be hidden by default",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="test_stale_threshold",
            field=models.DurationField(
                default=datetime.timedelta(days=30),
                help_text="Tests older than this will be pruned automatically",
            ),
        ),
    ]
