# Generated by Django 5.2 on 2025-04-18 15:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_project_test_thresholds"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="branch_inactive_threshold",
            field=models.DurationField(
                default=datetime.timedelta(days=7),
                help_text="Branches older than this will be hidden by default",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="error_indicators",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
