# Generated by Django 5.2 on 2025-04-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_project_branch_inactive_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="disabled",
            field=models.BooleanField(
                default=False, help_text="Forces the test to be disabled"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="average_duration",
            field=models.FloatField(default=-1, editable=False),
        ),
        migrations.AlterField(
            model_name="test",
            name="block_rate",
            field=models.FloatField(
                default=-1,
                editable=False,
                help_text="Effective failure rate with reruns and disabled excluded",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="enabled",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Test is allowed to block merges and releases",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="failure_rate",
            field=models.FloatField(
                default=-1,
                editable=False,
                help_text="Total failure rate on significant branches including reruns",
            ),
        ),
    ]
