# Generated by Django 5.2 on 2025-04-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_test_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="disabled_platforms",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Platforms to limit the disabled override",
            ),
        ),
    ]
