# Generated by Django 5.2 on 2025-04-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_test_disabled_platforms"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="disabled_reason",
            field=models.TextField(
                blank=True, default="", help_text="Reason for disabling the test"
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="disabled_tracker",
            field=models.URLField(
                blank=True,
                help_text="URL to the issue or ticket tracking the work to restore the test",
                null=True,
            ),
        ),
    ]
