# Generated by Django 5.2 on 2025-04-29 17:49

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0030_project_results_stale_threshold"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="results_stale_threshold",
            new_name="result_stale_threshold",
        ),
        migrations.AlterField(
            model_name="project",
            name="test_inactive_threshold",
            field=models.DurationField(
                default=datetime.timedelta(days=7),
                help_text="Tests with no results this recent time will be hidden by default",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="test_stale_threshold",
            field=models.DurationField(
                default=datetime.timedelta(days=30),
                help_text="Tests with no results this recent time will be pruned automatically",
            ),
        ),
    ]
