# Generated by Django 5.2 on 2025-05-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_update_threshold_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cleaned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
