# Generated by Django 5.2 on 2025-05-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0032_project_cleaned_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="result",
            name="status",
            field=models.CharField(
                choices=[
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                    ("error", "Setup Error"),
                    ("timedOut", "Timed Out"),
                    ("interrupted", "Interrupted"),
                    ("xfailed", "Expected Failure"),
                    ("xpassed", "Unexpected Pass"),
                    ("disabled", "Ignored Failure"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="block_rate",
            field=models.FloatField(
                default=-1,
                editable=False,
                help_text="Effective failure rate with reruns and ignored failures excluded",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="disabled_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Explanation of why the test is temporarily disabled",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="disabled_tracker",
            field=models.URLField(
                blank=True,
                help_text="URL of the ticket tracking the work to restore the test",
                null=True,
            ),
        ),
    ]
