# Generated by Django 5.2 on 2025-05-11 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0033_update_help_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cleaned_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="repository",
            field=models.URLField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="result",
            name="branch",
            field=models.CharField(db_index=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="result",
            name="commit",
            field=models.CharField(db_index=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="result",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="result",
            name="final",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indicates this was the final retry",
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="platform",
            field=models.CharField(
                choices=[
                    ("macos", "macOS"),
                    ("windows", "Windows"),
                    ("linux", "Linux"),
                ],
                db_index=True,
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="status",
            field=models.CharField(
                choices=[
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                    ("error", "Setup Error"),
                    ("timedOut", "Timed Out"),
                    ("interrupted", "Interrupted"),
                    ("xfailed", "Expected Failure"),
                    ("xpassed", "Unexpected Pass"),
                    ("disabled", "Ignored Failure"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="target",
            field=models.CharField(
                choices=[("web", "Web"), ("desktop", "Desktop")],
                db_index=True,
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="test",
            name="disabled",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Forces the test to be disabled"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="enabled",
            field=models.BooleanField(
                db_index=True,
                default=False,
                editable=False,
                help_text="Test is allowed to block merges and releases",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="name",
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="test",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(
                fields=["test", "branch", "commit"],
                name="projects_re_test_id_9aaab7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(
                fields=["test", "branch", "created_at"],
                name="projects_re_test_id_2d15ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(
                fields=["test", "status", "final"],
                name="projects_re_test_id_c80d23_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(
                fields=["project", "name"], name="projects_te_project_b91def_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(
                fields=["project", "disabled"], name="projects_te_project_279884_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(
                fields=["project", "enabled"], name="projects_te_project_6226c2_idx"
            ),
        ),
    ]
