# Generated by Django 5.2 on 2025-05-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0034_add_db_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="sample_count",
            field=models.IntegerField(
                default=100,
                help_text="Number of recent test results to consider in computed metrics",
            ),
        ),
    ]
