# Generated by Django 5.2 on 2025-05-14 14:11

import datetime

from django.db import migrations, models

import tab.projects.constants


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0035_project_sample_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="default_branches",
            field=models.JSONField(
                default=tab.projects.constants.get_default_branches,
                help_text="Results from these branches will be considered in computed metrics",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="error_indicators",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Message fragments that indicate there was a setup error rather than failure",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="test_inactive_threshold",
            field=models.DurationField(
                default=datetime.timedelta(days=7),
                help_text="Tests with no results this recent will be hidden by default",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="test_stale_threshold",
            field=models.DurationField(
                default=datetime.timedelta(days=30),
                help_text="Tests with no results this recent will be pruned automatically",
            ),
        ),
    ]
