# Generated by Django 5.2 on 2025-05-20 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0037_suite_test_suite"),
    ]

    operations = [
        migrations.AddField(
            model_name="suite",
            name="supports_override",
            field=models.BooleanField(
                default=False,
                help_text="Indicates the suite is configured to allow disabling tests",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="suite",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tests",
                to="projects.suite",
            ),
        ),
    ]
