# Generated by Django 5.2 on 2025-05-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0038_suite_supports_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="suite",
            name="local_command",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Pattern to run individual tests locally",
            ),
        ),
    ]
