# Generated by Django 5.2 on 2025-05-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0039_suite_local_command"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="disabled_reason",
            field=models.TextField(
                blank=True,
                db_index=True,
                default="",
                help_text="Explanation of why the test is temporarily disabled",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="disabled_tracker",
            field=models.URLField(
                blank=True,
                db_index=True,
                help_text="URL of the ticket tracking the work to restore the test",
                null=True,
            ),
        ),
    ]
