# Generated by Django 5.2 on 2025-06-10 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0041_result_suite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="suite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tests",
                to="projects.suite",
            ),
        ),
    ]
