# Generated by Django 5.2 on 2025-06-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0042_alter_test_suite"),
    ]

    operations = [
        migrations.AddField(
            model_name="suite",
            name="average_duration_lower_threshold",
            field=models.FloatField(
                default=30, help_text="Lower threshold to consider acceptable"
            ),
        ),
        migrations.AddField(
            model_name="suite",
            name="average_duration_upper_threshold",
            field=models.FloatField(
                default=60, help_text="Upper threshold to consider unacceptable"
            ),
        ),
        migrations.AddField(
            model_name="suite",
            name="block_rate_lower_threshold",
            field=models.FloatField(
                default=0.05, help_text="Lower threshold to consider acceptable"
            ),
        ),
        migrations.AddField(
            model_name="suite",
            name="block_rate_upper_threshold",
            field=models.FloatField(
                default=0.25, help_text="Upper threshold to consider unacceptable"
            ),
        ),
        migrations.AddField(
            model_name="suite",
            name="failure_rate_lower_threshold",
            field=models.FloatField(
                default=0.1, help_text="Lower threshold to consider acceptable"
            ),
        ),
        migrations.AddField(
            model_name="suite",
            name="failure_rate_upper_threshold",
            field=models.FloatField(
                default=0.5, help_text="Upper threshold to consider unacceptable"
            ),
        ),
    ]
