# Generated by Django 5.2 on 2025-06-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0043_suite_thresholds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="result",
            name="branch",
            field=models.CharField(db_index=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="test",
            name="original_branch",
            field=models.CharField(default="", max_length=500),
        ),
    ]
