# Generated by Django 5.2 on 2025-07-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0044_longer_branch_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="suite",
            name="tests_count",
            field=models.IntegerField(default=-1, editable=False),
        ),
    ]
