# Generated by Django 5.2 on 2025-07-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0046_alter_result_suite"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="skipped_indicators",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Message fragments that indicate a passed test was not actually able to run",
            ),
        ),
        migrations.AddField(
            model_name="suite",
            name="error_indicators",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Message fragments that indicate there was a setup error rather than failure",
            ),
        ),
        migrations.AddField(
            model_name="suite",
            name="skipped_indicators",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Message fragments that indicate a passed test was not actually able to run",
            ),
        ),
    ]
