# Generated by Django 5.2 on 2025-07-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0047_skipped_indicators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="average_duration",
            field=models.FloatField(
                default=-1,
                editable=False,
                help_text="Seconds duration from recent runs on significant branches",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="original_branch",
            field=models.CharField(
                default="",
                help_text="Name of the branch that originally added this test",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="original_commit",
            field=models.CharField(
                default="",
                help_text="Hash of the commit that originally added this test",
                max_length=100,
            ),
        ),
    ]
