# Generated by Django 5.2 on 2025-07-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0048_more_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suite",
            name="supports_override",
            field=models.BooleanField(
                default=True,
                help_text="Indicates the suite is configured to allow disabling tests",
            ),
        ),
    ]
