# Generated by Django 5.2 on 2025-08-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0049_alter_suite_supports_override"),
    ]

    operations = [
        migrations.AlterField(
            model_name="result",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("macos", "macOS"),
                    ("windows", "Windows"),
                    ("linux", "Linux"),
                ],
                db_index=True,
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="target",
            field=models.CharField(
                blank=True,
                choices=[("web", "Web"), ("desktop", "Desktop")],
                db_index=True,
                max_length=100,
                null=True,
            ),
        ),
    ]
