# Generated by Django 5.2.4 on 2025-08-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0050_optional_platform_and_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suite",
            name="block_rate_lower_threshold",
            field=models.FloatField(
                default=0.01, help_text="Lower threshold to consider acceptable"
            ),
        ),
        migrations.AlterField(
            model_name="suite",
            name="block_rate_upper_threshold",
            field=models.FloatField(
                default=0.05, help_text="Upper threshold to consider unacceptable"
            ),
        ),
    ]
