# Generated by Django 5.2.4 on 2025-08-09 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0051_lower_suite_block_rate_defaults"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="suite",
            options={"ordering": ["name"]},
        ),
    ]
