# Generated by Django 5.2.4 on 2025-08-14 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0052_alter_suite_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="suite",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="projects.suite",
            ),
        ),
    ]
