# Generated by Django 5.2.6 on 2025-09-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0053_suite_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="disabled_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp when the test was disabled",
                null=True,
            ),
        ),
    ]
