# Generated by Django 5.2.6 on 2025-09-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0054_test_disabled_at"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="test",
            name="projects_te_project_279884_idx",
        ),
        migrations.RemoveField(
            model_name="test",
            name="disabled",
        ),
        migrations.AlterField(
            model_name="test",
            name="disabled_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp of when the test was disabled",
                null=True,
            ),
        ),
    ]
