# Generated by Django 5.2.6 on 2025-09-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0055_remove_test_disabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="disabled_platforms",
        ),
    ]
