# Generated by Django 5.2.7 on 2025-10-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0056_remove_test_disabled_platforms"),
    ]

    operations = [
        migrations.RenameField(
            model_name="test",
            old_name="metadata",
            new_name="original_metadata",
        ),
    ]
