# Generated by Django 5.2.7 on 2025-10-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0057_rename_test_original_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="sample_count",
        ),
    ]
