# Generated by Django 5.2.7 on 2025-10-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0058_remove_project_sample_count"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="suite",
            unique_together={("project", "name")},
        ),
    ]
