# Generated by Django 5.2.7 on 2025-10-31 00:00

from django.db import migrations
from django.db.models import Count


def remove_duplicate_tests(apps, schema_editor):
    """Remove duplicate tests, keeping the oldest one."""
    Test = apps.get_model("projects", "Test")
    Result = apps.get_model("projects", "Result")

    # Find all duplicate (project, name) combinations
    duplicates = (
        Test.objects.values("project", "name")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )

    deleted_count = 0
    for dup in duplicates:
        # Get all tests with this project+name combination
        tests = Test.objects.filter(project=dup["project"], name=dup["name"]).order_by(
            "created_at"
        )

        # Keep the oldest test
        keeper = tests.first()
        duplicates_to_delete = tests.exclude(id=keeper.id)

        # Reassign any results from duplicate tests to the keeper
        for test in duplicates_to_delete:
            Result.objects.filter(test=test).update(test=keeper)

        # Delete the duplicates
        count = duplicates_to_delete.count()
        duplicates_to_delete.delete()
        deleted_count += count

    if deleted_count > 0:
        print(f"Removed {deleted_count} duplicate tests")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("projects", "0059_alter_suite_unique_together"),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_tests, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="test",
            unique_together={("project", "name")},
        ),
    ]
