# Generated by Django 5.2.9 on 2025-12-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0062_update_result_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suite",
            name="tests_count",
        ),
    ]
