# Generated by Django 5.2.9 on 2026-01-05 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0063_remove_suite_tests_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch", models.CharField(db_index=True, default="", max_length=500)),
                ("commit", models.CharField(db_index=True, default="", max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "setup_started_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "tests_started_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "tests_finished_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "teardown_finished_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="projects.project",
                    ),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="projects.suite",
                    ),
                ),
            ],
            options={
                "ordering": ["-setup_started_at"],
                "unique_together": {("project", "suite", "branch", "commit")},
            },
        ),
    ]
