# Generated by Django 6.0.6 on 2026-06-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0065_update_results_index_for_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="suite",
            name="average_setup_duration",
            field=models.FloatField(
                default=-1,
                editable=False,
                help_text="Seconds of setup duration from recent runs on default branches",
            ),
        ),
    ]
