# Generated by Django 6.0.6 on 2026-07-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0066_suite_average_setup_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="name",
            field=models.CharField(db_index=True, max_length=4000),
        ),
    ]
