# Generated by Django 5.2 on 2025-04-11 00:31

from django.db import migrations, models

import tab.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email_domain", models.CharField(max_length=100)),
                ("repository_index", models.URLField(unique=True)),
                (
                    "key",
                    models.CharField(
                        default=tab.core.models.generate_key, max_length=32, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
