# Generated by Django 5.2 on 2025-04-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_optional_email_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="repository_token",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
