# Generated by Django 5.2 on 2025-06-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_organization_repository_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="github_app_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="github_app_private_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
