# Generated by Django 5.2 on 2025-07-29 22:41

import tab.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_github_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='github_app_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='GitHub App ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='github_app_private_key',
            field=models.TextField(blank=True, null=True, verbose_name='GitHub App private key'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='key',
            field=models.CharField(default=tab.core.models.generate_key, max_length=32, unique=True, verbose_name='API key'),
        ),
    ]
