# Generated by Django 5.2.5 on 2025-09-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_organization_verbose_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="slack_bot_token",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Slack bot token"
            ),
        ),
    ]
