# Generated by Django 5.2.7 on 2025-10-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="environment",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="environment",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch", models.CharField(db_index=True, default="", max_length=500)),
                ("commit", models.CharField(db_index=True, default="", max_length=100)),
                ("results_passed", models.IntegerField(default=0)),
                ("results_total", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "tested_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="releases.environment",
                    ),
                ),
            ],
        ),
    ]
