# Generated by Django 5.2.7 on 2025-10-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0002_alter_environment_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="release",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="release",
            unique_together={("environment", "commit")},
        ),
    ]
