# Generated by Django 5.2.7 on 2025-11-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0003_alter_release_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="release",
            old_name="results_total",
            new_name="results",
        ),
        migrations.RemoveField(
            model_name="release",
            name="results_passed",
        ),
        migrations.AddField(
            model_name="release",
            name="finalized_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
