# Generated by Django 5.2.9 on 2025-12-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0004_release_finalized_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True, related_name="dependents", to="releases.environment"
            ),
        ),
    ]
