# Generated by Django 5.2.9 on 2025-12-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0005_environment_dependencies"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="environment",
            options={
                "ordering": [
                    models.Case(
                        models.When(name="local", then=models.Value(1)),
                        models.When(name="preview", then=models.Value(2)),
                        models.When(name="staging", then=models.Value(3)),
                        models.When(name="production", then=models.Value(4)),
                        output_field=models.IntegerField(),
                    ),
                    "project__repository",
                ]
            },
        ),
        migrations.AlterField(
            model_name="environment",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="URL"),
        ),
    ]
