# Generated by Django 5.2.9 on 2025-12-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0006_alter_environment_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="dependents",
                to="releases.release",
            ),
        ),
    ]
