# Generated by Django 5.2.9 on 2025-12-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0008_update_preview_label_to_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environment",
            name="url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="URL"
            ),
        ),
    ]
