# Generated by Django 6.0.3 on 2026-03-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0009_alter_environment_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="environment",
            options={
                "ordering": [
                    models.Case(
                        models.When(name="local", then=models.Value(1)),
                        models.When(name="review", then=models.Value(2)),
                        models.When(name="staging", then=models.Value(3)),
                        models.When(name="production", then=models.Value(4)),
                        output_field=models.IntegerField(),
                    ),
                    "project__repository",
                    "created_at",
                ]
            },
        ),
    ]
