# Generated by Django 6.0.7 on 2026-08-11 17:44

from django.db import migrations, models


def backfill_placeholder(apps, schema_editor):
    Environment = apps.get_model("releases", "Environment")
    Environment.objects.filter(url__contains="{").update(placeholder=True)


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0011_dedupe_review_environments"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="placeholder",
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.RunPython(backfill_placeholder, migrations.RunPython.noop),
    ]
